{{- if and .Values.config.data.security.jwt.key (eq .Values.config.data.security.jwt.key "CHANGE_ME_IN_PRODUCTION") (eq .Values.config.data.env "prod") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nav.fullname" . }}-jwt
  labels:
    {{- include "nav.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-key: {{ .Values.config.data.security.jwt.key | quote }}
{{- end }}
